### ISSUE TITLE
Key Storage Page Title ("Active Keys") Text is white

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Android_NFC_Ring_Unlock#1]

**Comment by xxv** [comment]
Additionally, other places throughout the app use white text. The "key and +" icon in the action bar of the key management screen is also white and thus hard to see.

**Comment by JohnMcLear** [comment]
I will sort this.  @xxv any chance of some screenies of the pages you have most beef with?

**Comment by xxv** [comment]
This seems to still be an issue in the published version. The icon was fixed, but the text is still white. See:

http://staticfree.info/~steve/tmp/Screenshot_2014-01-26-21-51-09.png
