### ISSUE TITLE
Lag time between screen wake & unlock app

### ISSUE THREAD

**Issue by TheCustomCave** [mclear/Android_NFC_Ring_Unlock#10]
Not sure if bug or feature but there's between a 1 & 5 second delay (depending on background apps) between lighting the screen up and the lock screen appearing.

If it's a long delay then it could provide enough time for someone to use an app killer shortcut to kill the lock screen before it loads.

**Comment by r2DoesInc** [comment]
I have to wait till Android tells me the screen is on. If they are late devliering the message, the app is late responding. Nothing to be done there :(

**Comment by TheCustomCave** [comment]
What about maybe artificially blacking the whole screen on screen off so that you at least don't see the homescreen when you light the phone back up again?

**Comment by r2DoesInc** [comment]
Even if that were possible, how would I know when to do it? Again, the
issue is that if the OS doesnt tell me the screen has come back on, I
cannot respond. The delay is a lag between when the device turns on and the
system tells me it has, not between when the system tells me its on and
when i respond.

**Comment by xxv** [comment]
could you intercept the screen off signal and quickly throw up a system-modal window?

**Comment by JohnMcLear** [comment]
Does this lag time affect security at all?

**Comment by r2DoesInc** [comment]
This "lag" is current in the main application as well. It is what it is and
I do not think it can be changed. I activate when the OS tells me to, there
really isn't anything else I can do.

**Comment by r2DoesInc** [comment]
fixed
