### ISSUE TITLE
Pin entry screen

### ISSUE THREAD

**Issue by LittleJohnD** [mclear/Android_NFC_Ring_Unlock#100]
Hi, running app version 1.5.1112 and android 4.4.2 HTC one.
1) Sometimes when you are typing in your pin if you delete everything because of a mistake when you return to the main screen and then again to the pin screen sometimes the 1st number remains

2)When you type the pin in a asterisk appears with the plain text number next to it then it disappears.

**Comment by LittleJohnD** [comment]
On point 2 the reason I bring it up is it is different for the pin entry screen if you are entering the unlock app

**Comment by JohnMcLear** [comment]
@r2DoesInc any thoughts on this?

**Comment by JohnMcLear** [comment]
Bump @r2DoesInc

**Comment by JohnMcLear** [comment]
@LittleJohnD @r2DoesInc I can confirm #2, I can't confirm #1.

RE #2, it's really not an issue is it?  Does it matter if the experience is slightly different?  Feels slightly pedantic no?

@r2DoesInc any idea if this is a quick fix?

**Comment by JohnMcLear** [comment]
Oh I just replicated #1..  Weird..  Had to go to PIN unlock screen, then power off/on my screen a few times and cycle until it replicated...  Again pretty minor..

Also I think having the NFC Ring Unlock app asking for pin to unlock that app might affect it?

**Comment by LittleJohnD** [comment]
Number 2 is pedantic but I thought I would make you aware of it as I thought they would be the same action object. 
Yep 1 isn't massive it is just again something that I thought you might want to know. Doesn't need a fix but I thought you would want to know all your bugs.

Cheers
