### ISSUE TITLE
Action on incoming call

### ISSUE THREAD

**Issue by LittleJohnD** [mclear/Android_NFC_Ring_Unlock#101]
Hi, running app version 1.5.1112 and android 4.4.2 HTC one.

1)If you receive an incoming call whilst unlocked then the app will lock the phone before you can answer it.

**Comment by r2DoesInc** [comment]
you can modify the call settings to change this behavior

**Comment by LittleJohnD** [comment]
I want it to have to be unlocked if the phone rings in my pocket or such but if I am already using my phone such as texting etc and I receive an incoming call I want it to stay unlocked so that I don't have to unlock it before I answer. I haven't received a ring yet (as I am still waiting for the stealth bomber collection) so I am testing on an RFID card. This means unlocking is tedious process just right now
