### ISSUE TITLE
Check security: PIN unlock

### ISSUE THREAD

**Issue by LittleJohnD** [mclear/Android_NFC_Ring_Unlock#104]
I believe that pins are mandatory I have one less security because I have pin unlock enabled is this meant to be or a throw back from older versions?

**Comment by JohnMcLear** [comment]
Afaik PINS are for graceful fallback and recommended, you can turn them off though...

**Comment by LittleJohnD** [comment]
Sorry that wasn't clear. With the pin unlock setting enables the security report reads 19/20 but I thought it was compulsory for when the phone is in airplane mode.
