### ISSUE TITLE
GMail password is not a password input field

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Android_NFC_Ring_Unlock#105]
So when you type it in you can see what you have typed in.

**Comment by iknowyerbad** [comment]
May I ask why the password box is not a password input field?
I am just a little curious on this one.

**Comment by Lokki-P** [comment]
That's the issue, it needs to become a password input field so you aren't seeing or inadvertently adding your password to the dictionary.

**Comment by iknowyerbad** [comment]
Exactly my thoughts.

**Comment by JohnMcLear** [comment]
Fixed
