### ISSUE TITLE
Disable sound notification

### ISSUE THREAD

**Issue by lemmings67** [mclear/Android_NFC_Ring_Unlock#106]
When your are scanning the ring to unlock, there is a sound notification that indicate that it's unlocked : I want to disable this...

**Comment by JohnMcLear** [comment]
Duplicate of https://github.com/mclear/Android_NFC_Ring_Unlock/issues/43

**Comment by lemmings67** [comment]
I found the solution : use Xposed + NFC LookScreenOff Enabler :+1: http://repo.xposed.info/module/pk.qwerty12.nfclockscreenoffenabler
