### ISSUE TITLE
Can't uninstall NFC unlock Galaxy S3

### ISSUE THREAD

**Issue by jazim** [mclear/Android_NFC_Ring_Unlock#107]
I have a Samsung S3 and can not uninstall the NFC unlock app.  I have turned off NFC and the application and it is still locking my phone.  This is extremely frustrating.  At this point I just want it gone from my phone.

**Comment by JohnMcLear** [comment]
Do you have a forum post that explains the process you have gone through?

----- Reply message -----

**Comment by jazim** [comment]
1. Unlock phone
2.  Go to apps in lower right corner
3.  from menue select the unistall open
4.  For NFC unlock click on the upper right corner where it shows the red dash which normally uninstalls an app.
5.  Nothing happens.  won't go away

The locking of the phone is happening randomly which is even more annoying because it is not repeatable and just happens at random times.

Do you need more information

**Comment by JohnMcLear** [comment]
Well you didn't answer my question...

Do you have a forum post that explains the process you have gone through?

**Comment by jazim** [comment]
no.  what forum? where?

**Comment by jazim** [comment]
Tell me what i need to do to try and get a resolution

**Comment by JohnMcLear** [comment]
Post on http://forum.nfcring.com/ -- Thanks :)
