### ISSUE TITLE
"Android L" Crash

### ISSUE THREAD

**Issue by lktmaster** [mclear/Android_NFC_Ring_Unlock#108]
This is all, in android L preview crash always, its unusable

**Comment by JohnMcLear** [comment]
This will be an android l bug but can remain open for posterity

----- Reply message -----

**Comment by TJ-G** [comment]
So, no support for androidL... ever? A bit puzzled by the "wonfix" tag.

**Comment by JohnMcLear** [comment]
Ah, meant to flag as we don't need to fix.  It will be fixed when L hits production
----- Reply message -----

**Comment by TJ-G** [comment]
Ah, that makes more sense :) Thanks for the clarification. Running the L preview now, and have been missing the unlock, thanks.

**Comment by JohnMcLear** [comment]
Yeah

Hopefully they haven't deprecated some apis we use...  Watch this space

----- Reply message -----

**Comment by JohnMcLear** [comment]
Fixed :)
