### ISSUE TITLE
Possible inspiration

### ISSUE THREAD

**Issue by TheCustomCave** [mclear/Android_NFC_Ring_Unlock#11]
Decided to test a theory while I'm waiting to get the ring. The Samsung Galaxy S4 will happily read (and unlock) through the strap on a pebble. I think this will be my master unlock tag until the ring arrives.

25mm NTAG203 stickers through 4mm of silicone strap.

![epic pebble-strap unlock](https://f.cloud.github.com/assets/6325047/1847578/d300396a-7655-11e3-9a3f-de4320452e79.png)

**Comment by JohnMcLear** [comment]
Cool :) Also try the smartrac midas tags, they will work fine too
