### ISSUE TITLE
password forum on email login doesn't work

### ISSUE THREAD

**Issue by beefmaster** [mclear/Android_NFC_Ring_Unlock#111]
on the android version of the lock app there is  a security flaw,
the flaw when you enable email login you can see what the password is that some one is entering.
this means that any one looking at your phone at the time you login can login later.

this is a product crippling bug and should be fixed imediatly

**Comment by JohnMcLear** [comment]
Duplicate of https://github.com/mclear/Android_NFC_Ring_Unlock/issues/105
