### ISSUE TITLE
Application enables itself

### ISSUE THREAD

**Issue by Myth010** [mclear/Android_NFC_Ring_Unlock#112]
Some time after boot the app enables itself and requires your ring. A bit annoying, especially since the first time this happened was after a custom rom install when I had no ring registered yet. This meant I had to boot to recovery to remove/rename the app. Could you please make it check if it's enabled in the settings and THEN have it do it's thing. And when disabled, not lock you out randomly..

**Comment by JohnMcLear** [comment]
1) The app shouldn't do this, we fixed this months ago, ensure you are running the latest version
2) If you are running a custom rom(so are rooted) there are better ways to unlock your phone with NFC.  NFC Ring Unlock provides some nice features but you have better options as we have to do a lot of hacking to work around Google's restrictions, I'd post on the forum to see what other people are using: https://forum.nfcring.com/category/8/nfc-ring-apps
