### ISSUE TITLE
Clock on Lockscreen

### ISSUE THREAD

**Issue by sicjay** [mclear/Android_NFC_Ring_Unlock#114]
Sometimes doesn't work after waking up. I marked the SweetSpots on the case so i know where to put the ring. Still, every second time or so when i try to unlock with the ring it doesn't work and i either have to unlock with the PIN or put the phone to sleep and reawake it. Sometimes i had to use the "Back"-Button before it worked again. To sum it up: Sometimes it works, sometimes it doesn't.
Hi there,

would it be possible to implement a clock on the lockscreen - it's kinda unhandy if i have to unlock the Handy everytime i want to know the time. Other stuff like NewMessageCount or such could be useful, but a clock is very necessary.

Kind Regards,
sicjay

**Comment by JohnMcLear** [comment]
clock on lockscreen is available for beta testers, sign up and let me know what you think :) 

Please provide a way to replicate the unlock not working each time.

**Comment by sicjay** [comment]
Hi,

after some testing i found my mobile has two "SweetSpots" and depending on whether i hold the ring horizontal or vertical (relative to the mobile) either the one or the other spot works. Vertical only works on the right one and horziontal only on the left one. So i think that maybe is an issue of my phone?

**Comment by JohnMcLear** [comment]
I'd say you need to +1 this https://github.com/mclear/Android_NFC_Ring_Unlock/issues/103
