### ISSUE TITLE
when will the source code be released and when will development actually start

### ISSUE THREAD

**Issue by beefmaster** [mclear/Android_NFC_Ring_Unlock#118]
hi,

i kick started this project and have received my ring.

when i download the app and installed it, it was functional then i started to in counter a massive amount of crucial bugs that need to be fixed.

when i last came on to assist with the development of this app the administrator said that they will release the source code of the app when they receive and open source license. since then that has been taking own and the source code has still not been released.

**Comment by JohnMcLear** [comment]
http://blog.nfcring.com/unicorn/nfc-ring-unlock-in-android-core/
