### ISSUE TITLE
Back button doesn't work in app

### ISSUE THREAD

**Issue by crazymuffins** [mclear/Android_NFC_Ring_Unlock#12]
Hi, 

The back button does not work in the unlock app at this stage. Once you select a option/menu item you have to close the app to go back. Bit of a pain =)

HTC One
Android 4.3

**Comment by JohnMcLear** [comment]
Really?  I just tested this and it works for me..  Can you provide exact steps to replicate?

**Comment by crazymuffins** [comment]
Sorry John,

I just noticed this bug report area is for the Unlock app not NFC Ring Control. My mistake. =) (Unlock app is great!) 

The issue is with the Ring Control app...

**Comment by JohnMcLear** [comment]
You still aren't making any sense but I'm going to assume you meant the bug was on the Control app, if that's the case this issue was closed an you will get an update on your device within the next 24 hours or you can force an update and it will get the fixed version.

J :)
