### ISSUE TITLE
Poor initial UX - Back button not going to login page when it should

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Android_NFC_Ring_Unlock#14]
It just took me 20 minutes to realize that to log in to the app, my email can't have ANY capitalization, even though your email showed that I should input my email address with a capitalized first letter. Please fix that!! It doesn't make any sense to prevent someone from logging in just because they have a capitalized letter. Also, "This app comes at no cost to the owners of NFC Ring. Without proper verification this app will not be usable" is definitely not a helpful error message. And pressing the back button should go back to the log-in screen instead of completely exiting the app. I had to re-open the app every time I wanted to try and log in!

**Comment by r2DoesInc** [comment]
i believe i got it fixed.
