### ISSUE TITLE
PIN pad shown after NFC unlock

### ISSUE THREAD

**Issue by ckoehnen** [mclear/Android_NFC_Ring_Unlock#15]
DEVICE: Nexus 4, CM-11-M2
1. Configure without Android lock screen
2. configure application PW in NFC Unlock app
3. power off
4. power on
5. swipe right to show PIN pad (do not enter PIN)
6. power off
7. power on
8. use ring (NFC tag) to unlock
9. PIN pad is still shown and can by bypassed using device's back button

**Comment by JohnMcLear** [comment]
Unable to replicate using these steps.

**Comment by JohnMcLear** [comment]
@ckoehnen can you check your steps to replicate?  I can't seem to replicate..
