### ISSUE TITLE
Status bar and soft keys in Android 4.3 still accessible 

### ISSUE THREAD

**Issue by ckoehnen** [mclear/Android_NFC_Ring_Unlock#16]
Device Nexus4, CM-11-M2

When configures without Android lock screen, the unlock app is not full screen. The status bar is visible and accessible. Also the soft keys (back, home, taskMgr) are still working as device default and not caught by the unlock app. When seeing the NFC lock screen, I can still open the task manager and go to home screen, etc...

**Comment by TheCustomCave** [comment]
I'm still able to access the top bar on 4.2.2 too.

**Comment by Unubtanium** [comment]
I have the same on Nexus 7 2013, running nova launcher on top of 4.4.2

**Comment by r2DoesInc** [comment]
Turn off your system lockscreen and enable the "use with no lockscreen" option.
