### ISSUE TITLE
Crash closing NFC Ring Control app

### ISSUE THREAD

**Issue by steelejoe** [mclear/Android_NFC_Ring_Unlock#17]
The app crashed with the "Unfortunately NFC Ring Control has stopped ... " dialog. Did not capture the screenshot -- but it's the system dialog.

The sequence of events was:
1) install the app
2) open the app
3) app warns about NFC being off
4) turn NFC on via the statusbar pulldown
5) hit menu key
6) hit back 
7) open "Advanced Task Killer" to see whether it was still running.
Boom!

I am not sure where the relevant entries are in the logcat and it is too large to post here in its entirety (not that I would want to do that anyway). I can send an excerpt via email if desired. Or if I am missing an obvious way to attach the log output - let me know.

I am running a Samsung Galaxy S4 (Sprint) with Android 4.3 (kernel 3.4.0-1927016).

**Comment by JohnMcLear** [comment]
Wrong place but already resolved :) Thanks!
