### ISSUE TITLE
Will not unlock with registered tag after installed a new app for NFC 

### ISSUE THREAD

**Issue by Unubtanium** [mclear/Android_NFC_Ring_Unlock#18]
Info: Nexus 7 2013, Android 4.4.2.

All worked fine with my test tag and it did unlock fine. 
But then I installed NFC retag after setting up NFC unlock. 
And then when I tried to unlock again with my tag it DID not work. 
When I unlocked it with my Google user and pass I did see that Android was asking me what APP to do an action with.  So I did select the unlock app and it all works fine now, but just though you should know. 

Ove

**Comment by r2DoesInc** [comment]
You have to set the app as the default. Put it on the wiki if youd like.

**Comment by JohnMcLear** [comment]
How do you set the app as default after selecting another option then setting it not to prompt you again?  http://androidforums.com/application-development/542764-making-nfc-app-default-when-scanning-tag.html
http://forums.androidcentral.com/samsung-galaxy-note-3/337477-set-default-nfc-app.html

In System Settings->Apps->ALL you have to look for that app (in my case "Tags"), entering the details and tap Disable

**Comment by JohnMcLear** [comment]
@Unubtanium can you update the wiki with a guide for how to do this please? :) Thanks

**Comment by r2DoesInc** [comment]
If you install a new NFC app that would interfere with the app being the
default, it clears the default. Simply scanning the tag again on the
homescreen and selecting the app will reset this default.
