### ISSUE TITLE
Sometimes when you are on the lock screen using the correct NFC Tag doesn't work

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Android_NFC_Ring_Unlock#2]
The tag registers but no events are fired, you have to use the fallback gmail login to access your device.  We need to find steps to consistently replicate.

**Comment by ententeak** [comment]
I've tried this app with one of my NDEF tags (added to keys in app) on Samsung Galaxy S3 with CyanogenMod 11, 4.4 Kitkat and set the "no lockscreen" option on.  
When I've locked my phone, lockscreen app appeared with ring picture and "unlock ring" but it didn't recognise the tag at all... Not even the unlock ring (the one with keyboard icon) worked.. My old KitKat locker showed up for a second and jumped back to NFC Ring Unlock App immediately....
Only full restart helped...
I think the main problem is that CyanogenMod turns off the NFC sensor when the phone's locked.

**Comment by JohnMcLear** [comment]
Either turn off the lock screen or turn off the "no lock screen" option.

**Comment by ententeak** [comment]
Okay.. this work good...
