### ISSUE TITLE
Design Request: PIN pad theme

### ISSUE THREAD

**Issue by ckoehnen** [mclear/Android_NFC_Ring_Unlock#20]
Please, theme the PIN pad screen the same way as the lock screen. (black background, white text)

**Comment by JohnMcLear** [comment]
I've done as much as I can @r2DoesInc I may need your help to remove the title bar or to make it black with white text :) Ta

**Comment by JohnMcLear** [comment]
PS @r2DoesInc branch is "styling" on the repo
