### ISSUE TITLE
Store a tag without writing it

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Android_NFC_Ring_Unlock#21]
Say I have a motox and I want to use the ring to unlock my motox and my s5, well I can't..  Because the motox has a differnet ndef requirement than my s5 would as the motox uses motorolas login screen.  Either motorola or the nfc ring unlock app would need to budge OR the nfc unlock app allows new tags to be stored without them being written.

**Comment by xxv** [comment]
If it supported unlocking just based on RFID, I'd be able to use my Charlie Card (subway system card; Mifare Classic, fully-locked). That'd be a great backup in case something happened to my ring, as I keep it in my wallet.

**Comment by r2DoesInc** [comment]
This is not possible. I had a thought a while back when this was mentioned to basically create a third party nfc handler that would allow multiple records worth of data to be written to the tag inside one actual record. The app would then split that record and parse the data into its corresponding records allowing somthing like this to work, but that is a discussion for another time. This is not possible with the current technology and apis we currently have.

**Comment by JohnMcLear** [comment]
Ugh, Everything is possible, please never say "This is not possible" to me, that's my least favorite saying in the world..  I agree it's a bigger job though than what we have the resources for right now so I will leave this open but as an enhancement request.

**Comment by xxv** [comment]
If the app is in the foreground (e.g. the lockscreen is showing), it can listen for any and all NFC interactions. See https://github.com/xxv/rfid_front_door/blob/master/src/TagScanner/src/info/staticfree/android/taguid/TagUidActivity.java#L206 for an example of how to do it.

**Comment by r2DoesInc** [comment]
No, I'm sorry but it is not possible. Mimetype MUST be written to the tag,
otherwise the app will not be launched. There is NO way around this.
Services CANNOT register an nfcadapter to listen for foreground tags,
meaning that they MUST be triggered another way. The mimetype on the tag
triggers an activity launch that triggers the actual unlock.

This is not possible with the way the OS currently functions.

**Comment by xxv** [comment]
Ah, gotchya. Not having the lockscreen as an activity would certainly add all sorts of limitations on what you can do, so I see the challenges you need to work around here.

**Comment by ententeak** [comment]
so.. why can Tasker with "NFC Locale" plugin work without writing any data to tag, just by reading his ID ? (For example)
I'm using this almost half year with Samsung Tec Tiles with my own data writen on them.. 
One screen is from Tasker, the second one from NFC Reader...
![2014-01-12 06 07 55](https://f.cloud.github.com/assets/6324786/1895671/140c26c2-7b50-11e3-89cd-9251583ed824.png)
![2014-01-12 06 07 40](https://f.cloud.github.com/assets/6324786/1895672/140de570-7b50-11e3-82cc-aac6f12132d4.png)

and i'm using third party program - Tag Writer by NXP - to write data

**Comment by r2DoesInc** [comment]
These are completely different applications that function in absolutely
different ways. Behavior between the two apps will not be analogous.

**Comment by ententeak** [comment]
sorry, but i dont understand why is problem reading "Tag ID" instead of writen data. It's just different variable to call from the tag/ring

**Comment by r2DoesInc** [comment]
The tag id is used. Data written to tag is mime type data. Again, the
differences are vast and the behavior is not comparable.

**Comment by jasok2** [comment]
Plus 1 for this feature if its ever possible :)

**Comment by r2DoesInc** [comment]
this feature is not possible.
