### ISSUE TITLE
"Use with no lockscreen" option confusing

### ISSUE THREAD

**Issue by xxv** [mclear/Android_NFC_Ring_Unlock#23]
I'm confused by this option. What does it mean? The language is very confusing.

**Comment by r2DoesInc** [comment]
Enable it when youve turned off your system lockscreen.

**Comment by xxv** [comment]
What does it do?

**Comment by r2DoesInc** [comment]
It draws the app over the status bar and softkeys.
If you enable it with the lockscreen still on, itll draw over the system
lockscreen. unfortunatly, the nfc radio isnt enabled while the system
lockscreen is up, so you wouldnt be able to scan your key to get in.

**Comment by xxv** [comment]
Hm. It doesn't seem to work for me on 4.4 then. I turned on the option and still have access to the status bar and softkeys from the lockscreen. It does seem to draw over them (as in block part of them) but I can still interact with the controls from the bit that's exposed.

**Comment by xxv** [comment]
Additionally, if I have this option enabled (with the system lockscreen disabled), I can switch to the PIN entry screen and access the full status bar without anything blocking it. I've got a lot of easy-access shortcuts in my statusbar, so this basically means that someone can get access to my phone. 

I was able to successfully launch my Google Authenticator, and take a screenshot of it while it quickly animated between screens. All of this while my phone was supposedly locked.

**Comment by JohnMcLear** [comment]
Obvious security issue / bug here needs resolving ASAP

**Comment by r2DoesInc** [comment]
Its not possible. There is no way to prevent interaction with the status
bar as a userspace app. If I had system access or root I could disable
access, but for now the best thing you can do is use the "use with no lock
screen" option.

**Comment by xxv** [comment]
I'm using the "use with no lockscreen" option and from what you described, it's supposed to prevent access to the status bar. Unfortunately, at least on 4.4.2, it's not doing that.

**Comment by r2DoesInc** [comment]
Yes it does. I'm using it right now. You can pull the status bar down, but
other than that tiny sliver at the top, nothing is manageable.

**Comment by xxv** [comment]
Ah, I see. So the small bit of interaction is considered OK (personally, I disagree with this).

As I mentioned before, if I switch to the PIN unlock or the Google login, that's where I can get at the full status bar. 

See the screenshot below for what I mean:

![screenshot_2014-01-10-13-16-40](https://f.cloud.github.com/assets/124381/1889889/e3730f12-7a23-11e3-9d6b-0172e169f531.png)

**Comment by r2DoesInc** [comment]
Its not "considered ok" its the only possible option. As a userspace app, I
cannot prevent the status bar from being pulled down.

In the main NFCSecure app, the pin and gmail fallback options prevent the
status bar from being pulled down as well.

**Comment by xxv** [comment]
OK. So that bugfix will make it into this app too, yeah?

**Comment by JohnMcLear** [comment]
I'm in agreement with @xxv on this one FWIW

**Comment by xxv** [comment]
The PIN unlock screen and Gmail fallback does not prevent the status bar from being pulled down over it, even if "Use with no lockscreen" is enabled.

**Comment by r2DoesInc** [comment]
no longer true.
