### ISSUE TITLE
Lockscreen easy to disable

### ISSUE THREAD

**Issue by xxv** [mclear/Android_NFC_Ring_Unlock#24]
I was able to disable the lockscreen permanently with only physical access to the device and not the NFC tag. Steps to do this:
1. Start with a device that only uses the NFC Ring Unlock as the lockscreen and is currently locked.
2. Hold the power button and then hold the "power off" button to go to safe mode
3. Once the device is restarted, go to Android system settings → security → device administrators, disable NFC Ring Unlock from being an administrator.
4. Go to Settings → Apps → NFC Ring Unlock → Clear data
5. reboot device and there's no more lockscreen!

If you can do these steps very quickly, you can reboot the device without going to safe mode and do it before the NFC Ring Unlock app gets its boot triggered.

This is on a Nexus 5 running stock 4.4.2.

**Comment by r2DoesInc** [comment]
If you clear the data, the app no longer is enabled or has any keys. The app is only as secure as the OS allows it to be. 100% security needs to be built into the OS, not a third party app, but this app is the best option.

**Comment by xxv** [comment]
I recognize that Android has many limitations when it comes to integrating the locking functionality; clearly they need to expose more APIs to allow 3rd party integration. However the app claims to provide security, in fact it goes so far as to penalize you by using the PIN unlock provided by the app in its security visualization. 

Unsuspecting users will think that they are more secure than they would be using the PIN of the system lockscreen, when the actual security provided by the app is currently at "toy" level at best, IMO.

**Comment by r2DoesInc** [comment]
If you can boot into safe mode, you prevent the app from running. That right there is enough for you to get into a users contacts etc. This app gives the most security possible for a userspace app. I know john has plans to have this functionality built into the OS, this would allow for the levl of security i think you are hoping for. Until then, we work with what we are given.

**Comment by xxv** [comment]
I recognize that you have limitations, it's simply a matter of setting user expectations. A non-developer won't know the difference between the capabilities of a userspace app and the built-in lockscreen. If your app claims to be very secure, they will believe you. I recommend playing down all the security warnings you provide throughout the app, as they don't compare to the insecurity of the app as a whole. This is akin to putting three deadbolts on your front door, but only having a screen door for the back. Security is all about the weakest links (and perception of security).

As an aside, when the app was a device administrator, even in Safe Mode it blocked me from clearing the data. Is there perhaps a way to lock the device to being a device administrator?

**Comment by r2DoesInc** [comment]
The user must enable that setting, and its impossible to prevent the user
for disabling it.

Perhaps I can put more emphasis on that one specific setting.
