### ISSUE TITLE
A few minor text issues

### ISSUE THREAD

**Issue by xxv** [mclear/Android_NFC_Ring_Unlock#26]
- User-facing text reads "Pin" instead of the abbreviation, "PIN"
- Some options end in a period ("."). e.g. "Manage application passwords." (which is also not in Title Case.

**Comment by JohnMcLear** [comment]
@r2DoesInc did these fixes get into the last round of fixes?

**Comment by r2DoesInc** [comment]
Nope.

**Comment by JohnMcLear** [comment]
Seems worth doing no?

**Comment by r2DoesInc** [comment]
Can you get me a list if all the text issues you want addressed? If i have
a list itll be fine, i just dont want to have to go hunting for all the
issues.

**Comment by JohnMcLear** [comment]
Is only two issues afaik that contain them, I'm about to jump on a plane so prolly wayyy more difficult for me to do ;\

**Comment by JohnMcLear** [comment]
Done :)
