### ISSUE TITLE
Avoid activity transitions

### ISSUE THREAD

**Issue by xxv** [mclear/Android_NFC_Ring_Unlock#29]
The lockscreen `Activity` properly holds the system modal (save being able to interact with the status bar and home, back, etc. buttons). However when it starts the PIN unlock activity or google entry `Activity`, there's a transition where it shows whatever's underneath.

I've been able to successfully interact with the items below during this transition enough that were I malicious, I could have made a phone call or other single-tap actions.

Perhaps the lockscreen and PIN entry functionality could be encapsulated in `Fragment`s to prevent this `Activity` transition from occurring? Then the `Activity` could just swap out the `Fragment`s. It'd look slicker, too, and you could even add a fade animation if desired.

**Comment by r2DoesInc** [comment]
Unfortunately, this is not at all how the app works, I will avoid going into more detail about how it does, but there is no lockscreen "activity". 

This issue has been negated with some new features in the main NFCSecure base, its up to john whether he wants to have these features pulled over.

**Comment by JohnMcLear** [comment]
If it's a bug that means the app isn't performing as it should IE isn't actually providing full unlock functionality, the changes need to be pulled over to our branch and released.  

To be clear on this.  I'm not interested in adding additional DRM for bugfixes.

**Comment by r2DoesInc** [comment]
there would be no need for DRM, the app is already locked to your users, i
dont see any way or reason to lock it more?

**Comment by xxv** [comment]
(whoops, didn't mean to press that button)

**Comment by JohnMcLear** [comment]
Your additional ties our users to authenticate with a different third party than they have an agreement with (us) so it's not an option.  Please stop trying to force it upon us, I have stated a number of times I'm not interested and wont be reviewing for several months.
