### ISSUE TITLE
Double Unlock

### ISSUE THREAD

**Issue by billmans** [mclear/Android_NFC_Ring_Unlock#31]
Nexus 5
4.4.2

Our company requires (via policy) the use of pin unlock on my device. When I install NFC Unlock app I now get the standard Android unlock (with pin) and then the NFC Unlock screen.  Is there anyway to have NFC unlock replace the standard Android one?

**Comment by jasok2** [comment]
I would like to add to this. ( I also have a Nexus 5)  If you encrypt your phone by default it forces you to have a pin or password. So i agree it would be nice if the app could bypass or do this for you. I had to reset to factory defaults to un-encrypt the phone to set it up without a pin to get around the double unlock.

**Comment by r2DoesInc** [comment]
The only thing possible is to disable your system lockscreen. if you are required for whatever reason to have one in place, this is not a restriction you can avoid without disabling whatever feature set the restriction.
