### ISSUE TITLE
Phone stuck after deep discharge: SIM PIN screen + NFC Unlock on top cannot unlock!

### ISSUE THREAD

**Issue by mougino** [mclear/Android_NFC_Ring_Unlock#33]
After being too low battery my Xperia Z shut down itself. I recharged it, then upon reboot I see the SIM PIN code then immediately after the NFC Ring Unlock screen, the huge problem is the app seems unefective! I tried unlock with the ring half a hundred times, in all sort of positions, it never works (it worked fine before reboot).
If I slide the unlock button, I see the SIM PIN code screen some milliseconds, then the NFC Ring Unlock screen appears again. Unless I'm mistaken, my phone is bricked, no way to recover except a factory reset! Any feedback on how to bypass would be more than welcome.

**Comment by JohnMcLear** [comment]
Your phone wont be bricked, don't panic..  Let it charge up for a bit then do a normal reboot..

**Comment by mougino** [comment]
My phone is charged at 100%. I already hard-rebooted it 4 times (volume key + power button, as a long press on power button only displays a popup hidden behind the NFC Ring Unlock screen).
Is there a mechanism preventing the app to unlock the phone because it is in blocked on SIM PIN code screen?

**Comment by mougino** [comment]
OK, I found a workaround, but it's a little bit tricky... After rebooting the phone, the "NFC Ring Unlock screen" (I will call it NRUS) takes all the screen **except** 2 bands at the top (notification bar) and bottom of the screen (Emergency call button). The trick is to use the "Emergency call" button at the bottom: press it, you can see the lower band changed and presents a "back" and a "home" icons (the NRUS is still there, on top), at this moment press back, and **from this moment on** sliding the lock icon of the NRUS makes it disappear and you are **back in the SIM PIN code screen** where you can enter your SIM PIN code! After unlocking the SIM, you arrive on the special NFC Ring Unlock "sign in with your Gmail below" screen that you can discard with back key, the NRUS appears and this time the ring is recognized (phew!). After a first unlock, there is a 2nd NRUS, you can unlock it again with the ring, and bingo you're in Home!

Can you guys reproduce any of this? Now I'm able to access the settings, so I can give more info: it's a Sony Xperia Z (C6603) under Android 4.2.2. Tell me if you need help debugging or testing things.

**Comment by r2DoesInc** [comment]
You enabled the use with no lock screen method while you are clearly still using a lock screen. Disable your Sim pin if you want to enable that setting. 

Please use one of the fallback methods to unlock your device, with the lock screen underneath, your device hasn't activated the NFC radio, meaning its impossible to scan a tag

**Comment by mougino** [comment]
Wow, issue closed 1 minute after I hardly managed to find a solution, a little expeditious to my taste. So if I understand correctly it's not a bug it's a feature? Shouldn't it be mentioned somewhere? I struggled on this and found a workaround but most of your other customers who have a SIM PIN code (in my country all SIM cards have one by default) can feel lost here. Following your answer, I would recommend forcing the user to define a fallback method at time of enabling NFC Ring Unlock, or if no callback, show a popup with a checkbox "I understood that I must remove any other lock method such as SIM PIN code.. bla bla". Just an advice of course, you are the master of how your app is perceived by your customers.

**Comment by r2DoesInc** [comment]
We are planning in clarifying that feature to make it more user friendly.
Gmail fallback is built into the app and always accessible.

What you experienced is neither a bug nor a feature, but a behavior brought
on by misuse of the app.

**Comment by mougino** [comment]
Read the symptoms again and see that Gmail fallback doesn't work here, it is not accessible: sliding the lock icon, you see the SIM PIN code flashing, then back on NFC Ring Unlock screen, you can do that a hundred times it's always the same. Only the workaround above allows to get out of it.

**Comment by r2DoesInc** [comment]
There's a change coming soon that completely redoes the behavior of the
fallbacks, that behavior will be resolved at that time.

Please unchecked the use with no lock screen option in the future.

**Comment by mougino** [comment]
Thanks for your last answer, I did what you advised and indeed that fixes it!
Waiting for the new version now ;-)
