### ISSUE TITLE
NFC ring unlock app frozen

### ISSUE THREAD

**Issue by northan77** [mclear/Android_NFC_Ring_Unlock#34]
Hey John
It's Tim S from Kickstarter.
I just downloaded your NFC ring unlock app, I have has a few issues where the unlock screen does not accept the ring or manual pin entry. It's not like the app is frozen per se, just not changing state. I can see the animation and move to hover over the keypad, but it won't change.

I have a Note 2 GT-N7100, android 4.1.2, rooted.
I've used a standard NFC tag.

Update;
Just deleted all the data and redone it again, all seems ok so far, but still I thought you might like to know about the issue.

On another note, I use an app called Cerberus to take a picture of a person if so many unsuccessful attempts have been made to unlock the phone. It will email me this picture. Is there any way that this app can interact with cerberus if the same case was to happen. I have a feeling I know how the response will go, but I thought I would ask.

**Comment by northan77** [comment]
Ok it seems because I still had a swipe to unlock feature still setup on the android settings and I had used the "use with no lockscreen" option.

**Comment by JohnMcLear** [comment]
Yea we're adding a popup alert about that to warn people to not enable it unless lockscreen is disabled :)
