### ISSUE TITLE
Check security highlights incoming calls

### ISSUE THREAD

**Issue by LittleJohnD** [mclear/Android_NFC_Ring_Unlock#35]
Hi, using a HTC one on jellybean. App inactive due to no tag yet.

When I check security it says that it is 19/20 incoming calls deactivate lock. The option is set to do not unlock but still detects wrong option. Tried change off then change back nothing.

**Comment by r2DoesInc** [comment]
Coups be related to the issue of the call settings not sticking. Will look into it.

**Comment by JohnMcLear** [comment]
@r2DoesInc did you manage to look into this?

**Comment by JohnMcLear** [comment]
@r2DoesInc bump again...

**Comment by r2DoesInc** [comment]
I think i addressed this a while back.

**Comment by JohnMcLear** [comment]
You wanna double check when you do some touches tomorrow?

**Comment by r2DoesInc** [comment]
Ya, if not itll be a quick fix.

**Comment by r2DoesInc** [comment]
Yup, its in.

public static int getMaxSecurityLevel() {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.JELLY_BEAN_MR2) {
            return 20;
        } else {
            return 19;
        }
    }

**Comment by JohnMcLear** [comment]
Eggs cement thanks :)
