### ISSUE TITLE
Cannot uninstall NFC Ring Unlock app

### ISSUE THREAD

**Issue by mougino** [mclear/Android_NFC_Ring_Unlock#36]
It is impossible to uninstall the NFC Ring Unlock app from my Xperia Z Android 4.2.2.

When I go in Settings > Applications it appears as "co.mclear.nfcringunlockpro" (package name) while all the other apps appear as their app name. Then when I tap to display the app details, both buttons "force stop" and "uninstall" are grayed (?)

Screenshot here: http://imgur.com/JBhm9rs

Also the Sony phones offer an uninstall option from the app menu, and here too the uninstall is deactivated for NFC Ring Unlock (although here it is listed under the correct app name).

Screenshot here: http://imgur.com/dqJv06c

**Comment by JohnMcLear** [comment]
Good spot, will test that now and report back.

**Comment by JohnMcLear** [comment]
Weirdly it is showing on my desktop as co.mclear.nfcringunlockpro despite the fact the manifest reads correctly..

**Comment by JohnMcLear** [comment]
The shortcut on my apps was perfect, so it';s just the desktop shortcut that's borked..

Uninstall worked perfect...

@mougino how did you install the app?  From the play store or?

**Comment by JohnMcLear** [comment]
Uninstall worked both ways for me, goign through settings and pressing and holding on app icon list screen and dragging to uninstall..

**Comment by mougino** [comment]
Ok after more investigation I managed to find the reason why it can't be uninstalled, it is when the option Device Security > Manage Device Administrator is enabled. It gives admin privileges to the app preventing it to be uninstalled by the user. Disable that option and you can uninstall the app the normal way.

**Comment by mougino** [comment]
And yes the app was installed from the Play Store.

**Comment by JohnMcLear** [comment]
@mougino good spot, would you mind whacking that on the Wiki please?  I think others will benefit from your discovery :)

**Comment by mougino** [comment]
Ok, done: https://github.com/mclear/Android_NFC_Ring_Unlock/wiki (last Q/A)
I am not a native English speaker so please rephrase any way you prefer and that is more understandable.

**Comment by JohnMcLear** [comment]
Excellent, cheers buddy :) I cleaned it up a bit too!

**Comment by bootstrapt** [comment]
Thanks for sharing the fix mougino. Had this issue and it started to get really annoying. Glad it was a quick fix.
