### ISSUE TITLE
user defined app allowed list

### ISSUE THREAD

**Issue by jasok2** [mclear/Android_NFC_Ring_Unlock#37]
Hi, you closed my bug about having to unlock the phone to allow responding to the alarm because there was nothing for the app to listen to.

so how about a user defined allowed list of apps that can run without having to unlock the "NFC_Ring_Unlock" app

for example I could specify my alarm app and my camera app to be allowed to run without having to unlock the "NFC_Ring_Unlock" app first.

I guess this is a feature request now, not so much a bug.

**Comment by r2DoesInc** [comment]
Not really possible. At that point, you basically have an app lock. I wrote this functionality a long time ago, had it working, but hated it so much I trashed it. To implement an app lock, you have to abuse some system APIs in a way that the engineers have specifically said not to. Its generally just a bad idea.
