### ISSUE TITLE
Strange behavior with "Use With No Lockscreen" when an android lockscreen is actually enabled.

### ISSUE THREAD

**Issue by pastudan** [mclear/Android_NFC_Ring_Unlock#39]
If you are using a pattern unlock (or any other standard Android unlock method) and enable the "Use With No Lockscreen" option, the app sometimes will not let you swipe to the Google sign in backup method, and when trying to do so, temporarily flash the underlying android lockscreen, then go immediately back to the NFC ring unlock screen.

The only way to get out of this loop is to reboot the phone.

I am using Cyanogenmod 11 on a GS3.

**Comment by JohnMcLear** [comment]
This is fixed in latest version :)
