### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by StylingAndroid** [mclear/Android_NFC_Ring_Unlock#4]
The list of permissions required by this app is pretty scary. Could you please provide an explanation in the Google Play listing of why each permission is required?

**Comment by JohnMcLear** [comment]
*Updated thanks to @r2DoesInc 

SYSTEM_ALERT_WINDOW - Draw lockscreen
WRITE_EXTERNAL_STORAGE <-- for db export
READ_EXTERNAL_STORAGE <-- for db export
GET_ACCOUNTS <-- get possible email fallback options
INTERNET <-- verification
VIBRATE <-- to vibrate
MANAGE_ACCOUNTS <-- to check if user signed in correctly with gmail
USE_CREDENTIALS <-- could honestly be removed. was related to some old stuff we wanted to do but never finished.
READ_PHONE_STATE <-- check internet connection
NFC <-- for nfc
RECEIVE_BOOT_COMPLETED <-- to detect when the phone starts
CAMERA <-- To take pictures of the ring you assigned as a key

**Comment by StylingAndroid** [comment]
Unfortunately, some of the "should be obvious" permissions are not obvious. For example SYSTEM_ALERT_WINDOW is a very scary permission. Even the Google docs state "Very few applications should use this permission; these windows are intended for system-level interaction with the user." Why is this required?

Also what is the deal with the "tba" permissions? Are they not actually required yet but there for future features? If so, then why not remove them until they _are_ required?

As previously stated, this permissions list is very scary. An app requiring these permissions could gather lots of personal information, and be very intrusive. I am not prepared to install this app because I do not have sufficient explanation of why all of these permissions are required.

**Comment by fgsguedes** [comment]
SYSTEM_ALERT_WINDOW is needed because its the way the app uses to lock your phone until you 'read' your ring, placing a alert windows above everything else.
It's not the way I expected it to work but it does the job, not a big of a deal.

**Comment by StylingAndroid** [comment]
So you are not using the standard lock mechanism? That has additional issues as it means that it is incompatible with any Enterprise / device  management policies. Bypassing the system security is not great, IMO

**Comment by fgsguedes** [comment]
I'm not part of the NFC Ring team, I just backed the project on Kickstarter the same way you probably did.
Sorry for the confusion.

**Comment by r2DoesInc** [comment]
He's right. NFC cannot be used when the device is locked by the android system. To get around that, I disregard androids security and created my own.

**Comment by Tragen** [comment]
So you say we won't have the normal lock screen anymore?
No widgets and no access to music or camera?

Still I don't know why this app needs
GET_ACCOUNTS <-- tba
MANAGE_ACCOUNTS <-- tba
USE_CREDENTIALS <-- tba
READ_PHONE_STATE <-- should be obvious

**Comment by r2DoesInc** [comment]
That is not what I said. If you use NFCSecure in conjunction with your
system lockscreen, nfcsecure will come up before or after the lockscreen
depending on your configuration. to use nfc to unlock your device, you scan
your tag on my lockscreen, not the system lockscreen.

**Comment by nkavian** [comment]
I agree with StylingAndroid.  Saying "tba" or "should be obvious" is not an answer.

For non-Android developers, it is absolutely not clear and it's disingenuous to tell them it's "obvious".

I happen to be an Android developer and you should understand that "GET_ACCOUNTS <-- tba" is still not fair.  Perhaps I should be asking where is the privacy policy for the App because now I have to start asking how my "accounts" via "GET_ACCOUNTS" is going to be used.

Thanks for tracking me down on Quora after I left my review on the Android Market.  I think a reasonable conclusion to this would be to share your Terms of Service, Privacy Policy, and an accurate explanation of how the permissions are used.

**Comment by JohnMcLear** [comment]
Hey @nkavian yea I agree I'm gonna get on with this, thanks for pushing me to action this.

**Comment by r2DoesInc** [comment]
SYSTEM_ALERT_WINDOW - Draw lockscreen
WRITE_EXTERNAL_STORAGE <-- for db export
READ_EXTERNAL_STORAGE <-- for db export
GET_ACCOUNTS <-- get possible email fallback options
INTERNET <-- verification
VIBRATE <-- to vibrate
MANAGE_ACCOUNTS <-- to check if user signed in correctly with gmail
USE_CREDENTIALS <-- could honestly be removed. was related to some old stuff we wanted to do but never finished.
READ_PHONE_STATE <-- check internet connection
NFC <-- for nfc
RECEIVE_BOOT_COMPLETED <-- to detect when the phone starts
CAMERA <-- To take pictures of the ring you assigned as a key

**Comment by r2DoesInc** [comment]
updated details

**Comment by JohnMcLear** [comment]
@nkavian let me know if you have further questions :)

**Comment by nkavian** [comment]
Thanks John.  I hope this will satisfy future inquiries.

**Comment by JohnMcLear** [comment]
Cheers @nkavian I still need to do our privacy policy and terms of service for you, will hopefully get time to do those late next week once we get these first rings shipped.
