### ISSUE TITLE
Better integration into Android lockscreen.

### ISSUE THREAD

**Issue by pastudan** [mclear/Android_NFC_Ring_Unlock#40]
I was under the impression this app would add another unlock method into the options within the OS settings. I would love to be able to use this with my standard android unlock methods as a backup, in case I lose my ring. Also, being able to use standard android lockscreen widgets would be huge. Unfortunately, it seems that if you want to enable a standard android unlock method and/or lockscreen widgets, you will need to use it in addition to NFC unlock? (for example, you'd have to enter your pattern AS WELL as tap your NFC ring?)

Can you let me know if there are plans for tighter android integration, or is this not currently possible?
- I'm sorry to open 3 separate issues in a row here, but I don't know of a better forum to ask them in.

**Comment by r2DoesInc** [comment]
It is the long term stretch goal, but nothing can be done presently.
