### ISSUE TITLE
Unable to change "disconnected phone call behavior"

### ISSUE THREAD

**Issue by karelkalivoda** [mclear/Android_NFC_Ring_Unlock#41]
Always I change this settings and exit, it changes back to "do not re-lock the device" option.
I have Samsung S III

**Comment by r2DoesInc** [comment]
Sounds like a bug I struggled with on the base app. I got it fixed there, will look into it here ASAP.

**Comment by JohnMcLear** [comment]
@r2DoesInc 2 months ago, any progress?

**Comment by r2DoesInc** [comment]
Yup, fixed.

**Comment by JohnMcLear** [comment]
\o/
