### ISSUE TITLE
NFC ring control app

### ISSUE THREAD

**Issue by northan77** [mclear/Android_NFC_Ring_Unlock#45]
I used the app to write text onto the ring, all fine. When coming to read the text with the same app, it always reads the text with "en" at the start of the text. 
Example write hello, comes out enhello.

**Comment by JohnMcLear** [comment]
Yea, I think the string is fine (read it outside of the app).

I have a feeling it's for some reason just appending two characters at the beginning of the string

https://github.com/mclear/NFC_Ring_Control/blob/master/www/js/index.js#L158 is the point we display the string..

cc'ing @don for posterity

**Comment by northan77** [comment]
yep string fine in external apps
