### ISSUE TITLE
Re-enabling security enforcement after auto update

### ISSUE THREAD

**Issue by nfcringtom** [mclear/Android_NFC_Ring_Unlock#46]
This was posted on the forum, is this supposed to happen?

"Incidentally, I'd scanned the spare tag into the NFC Ring Unlock program and tested it. I then disabled security enforcement as I didn't want to carry the spare tag around. After the last auto-update, it re-enabled security enforcement without being told to!

Fortunately you can type your gmail credentials to unlock, otherwise I would have been severely stuffed. Bug in the update, perhaps?"

http://forum.nfcring.com/post273.html#p273

**Comment by r2DoesInc** [comment]
Not sure, keep us informed if it re-enables itself again.

**Comment by JohnMcLear** [comment]
I guess this was a one off ;\
