### ISSUE TITLE
NFC Unlock lock appearing even though disabled/inactive

### ISSUE THREAD

**Issue by eberta** [mclear/Android_NFC_Ring_Unlock#47]
I am running across an issue where if I input my android pin wrong once and then enter the correct pin the second time, the NFC unlock screen shows up even though device security is inactive/disabled in the settings for NFC unlock.  I don't have NFC unlock enabled because I don't have an nfc tag yet to test with.  Luckily enough I can use the secondary input with my google credentials to get by the screen.

**Comment by casper181** [comment]
Same here.

I also have a problem where the Ring Unlock doesn't appear even when active unless I have the device locking using some other method (pattern lock for instance) and even then it's occasional.

Anyone have any ideas

Samsung Galaxy S4 i9505 4.4.2

**Comment by JohnMcLear** [comment]
@ebarta & @casper181 what version of the nfc ring unlock app are you running?

**Comment by eberta** [comment]
Version 1.5.7

**Comment by casper181** [comment]
1.5.7 for me too

On 10 March 2014 12:58, John McLear notifications@github.com wrote:

> @ebarta & @casper181 https://github.com/casper181 what version of the
> nfc ring unlock app are you running?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mclear/Android_NFC_Ring_Unlock/issues/47#issuecomment-37179036
> .

## 

[image: View Colin Aspinall's profile on
LinkedIn]http://uk.linkedin.com/in/colinaspinall

**Comment by casper181** [comment]
Looks like it only activates if I get the pattern unlock wrong more than
once.  Even though the settings are:

Delay Type: None

Colin

On 10 March 2014 12:58, John McLear notifications@github.com wrote:

> @ebarta & @casper181 https://github.com/casper181 what version of the
> nfc ring unlock app are you running?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mclear/Android_NFC_Ring_Unlock/issues/47#issuecomment-37179036
> .

## 

[image: View Colin Aspinall's profile on
LinkedIn]http://uk.linkedin.com/in/colinaspinall

**Comment by casper181** [comment]
Done some work on this now:
1. Doesn't matter whether active or not
2. Only triggers ring unlock if there is a failure of the other security method (in my case pattern unlock)
3. Therefore another security method MUST be active

Hope that helps

Colin

**Comment by JohnMcLear** [comment]
Thanks for this @casper181 very useful will bump @r2DoesInc

**Comment by casper181** [comment]
Am hoping my rings will arrive shortly. Without the app working the primary reason for buying them is a bit redundant - any update John?

**Comment by JohnMcLear** [comment]
@casper181 http://blog.nfcring.com

**Comment by casper181** [comment]
Thanks John - was expecting to see something relevant to my issue with the
app on there.  Was there any reason why you sent it on other than to tell
me my ring will be on its way this week (but still won't unlock my phone)?

On 17 March 2014 14:08, John McLear notifications@github.com wrote:

> @casper181 https://github.com/casper181 http://blog.nfcring.com
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mclear/Android_NFC_Ring_Unlock/issues/47#issuecomment-37818857
> .

## 

[image: View Colin Aspinall's profile on
LinkedIn]http://uk.linkedin.com/in/colinaspinall

**Comment by JohnMcLear** [comment]
Oh, wait..  you didn't specify which bit you wanted an update on..  You meant an update on the issue..  Yes.. @r2DoesInc is testing as of today.

**Comment by r2DoesInc** [comment]
I'm doing some more work with the app today. I haven't yet been able to
figure out why its locking when it shouodbt, and I still haven't seen that
behavior yet, but I'm keeping at it.

**Comment by casper181** [comment]
Any update on this locking /not locking issue?

**Comment by JohnMcLear** [comment]
We still haven't been able to replicate it :\

**Comment by casper181** [comment]
What do you need me to do. It is a permanent issue, not something that
happens now and again.  It is also connected to the other issue of it not
coming on if I don't have another lock method.

C

On 30 April 2014 02:44, John McLear notifications@github.com wrote:

> We still haven't been able to replicate it :\
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mclear/Android_NFC_Ring_Unlock/issues/47#issuecomment-41752555
> .

## 

[image: View Colin Aspinall's profile on
LinkedIn]http://uk.linkedin.com/in/colinaspinall

**Comment by stevenroose** [comment]
I had this too, had to uninstall the app. It only appeared when I entered an incorrect unlock pattern.

**Comment by r2DoesInc** [comment]
Thank you for the info.

**Comment by casper181** [comment]
@r2DoesInc if you need me to do any testing etc. please let me know. I'm obviously keen to get this sorted so if I can help in any way let me know.

**Comment by JohnMcLear** [comment]
Resolved :)
