### ISSUE TITLE
Check security level warns about lockscreen widget being activated even on 4.1.2 devices

### ISSUE THREAD

**Issue by fgsguedes** [mclear/Android_NFC_Ring_Unlock#5]
Going to "Application Security" -> "Check Security Level" on a 4.1.2 device the app will still warn you about a security issue caused by lockscreen widgets being enabled.

Going to "Device Secirity" and checking "Disable Lockscreen Features" removes the warning, but I think it shouldn't be necessary on those cases.

Tested on a Razr i running 4.1.2.

**Comment by r2DoesInc** [comment]
Fair observation.

**Comment by Unubtanium** [comment]
I had the same thing and i thought it was a bug, as I had disabled lockscreen widgets but STILL got the warning. Not untill i read about it here i found how to get 20/20

**Comment by r2DoesInc** [comment]
fixed
