### ISSUE TITLE
NFC ring unlock app feedback

### ISSUE THREAD

**Issue by kiwicscout** [mclear/Android_NFC_Ring_Unlock#50]
NFC ring unlock app feedback
there is a spelling mistake on the personalised security report

it says Enabled lockscreen widgets NFC unlock is most secure when the "incoming phone call behaviour" option is set to not diable the lock 
missing the s  :-) in disabled 
under lock screen customisation the custom lockscreen message "custom message to ndisplay on the lockscreen"
extra n on the start of the word display

when i had to do a manual login with email and password for the unlock app I understand the password being case sensitive but the email address is as well 
mine is all lower case but as my email is also my name my phone always auto corrects it to capitalise the first letter and I have to over ride it.

took me many attempts to discover this when I could not find my tag. ( no my tag is not on my finger I don't have my ring yet )

Under key storage i get a message Failed to backup keys database. File not found. when trying to back up they stored keys.

I also don't seem to be able to store more than one key to unlock the device is this working as designed? I would prefer to have a couple of tags able to unlock the phone.

**Comment by JohnMcLear** [comment]
@r2DoesInc any update on this?

**Comment by JohnMcLear** [comment]
Bump @r2DoesInc

**Comment by r2DoesInc** [comment]
resolved
