### ISSUE TITLE
Read only mode & Keyback up

### ISSUE THREAD

**Issue by MLWALK3R** [mclear/Android_NFC_Ring_Unlock#51]
Readonly mode, Could do with more info about read only mode e.g pros and cons, second stage warning maybe ?

Key Backup, Doesn't work on Nexus 5

**Comment by r2DoesInc** [comment]
Pros and cons would be pretty subjective. All it does is prevent the tag from being written to again, I feel like its pretty self explanatory.

Backup is broken, thank you.

**Comment by JohnMcLear** [comment]
Backup is broken is resolved?

**Comment by r2DoesInc** [comment]
Fixed.
