### ISSUE TITLE
Add support for multiple NDEF records

### ISSUE THREAD

**Issue by friode** [mclear/Android_NFC_Ring_Unlock#54]
I'd like to be able to unlock my phone with an inlay that has multiple NDEF records, where the nfcringunlock/key MIME record is _not_ the first record.

The first record is often used as the default by apps that don't support multiple NDEF records, and I'd like to use that record for a more sensible default (e.g. contact information or URL), whilst retaining the ability to unlock the phone with the same inlay.

Tested with http://ndefeditor.grundid.de/ and https://play.google.com/store/apps/details?id=com.antares.nfc

**Comment by r2DoesInc** [comment]
Not possible. The Android framework needs to know where to send the NFC event. If the mimetype is not available, another app will get the scan and the device will not unlock.

**Comment by friode** [comment]
You can't register to handle NDEF_DISCOVERED and read the individual NdefRecords in the NdefMessage to see if there's a match?

https://developer.android.com/guide/topics/connectivity/nfc/nfc.html#dispatching
https://developer.android.com/reference/android/nfc/NdefMessage.html

**Comment by r2DoesInc** [comment]
Weve had a bit of an internal discussion on this and have come to the
conclusion that, while possible, there is not really a practical way to do
this.

**Comment by friode** [comment]
Fair enough, this does reduce the utility of the ring somewhat, though.  There's no way for me to use one ring to 1) unlock my phone, 2) unlock my front door, and 3) have a url or contact information available.  And if I use the second inlay on a ring as a backup of the first, it limits it to only a single function.

**Comment by JohnMcLear** [comment]
Sure you can do all three just not a backup....

----- Reply message -----

**Comment by friode** [comment]
Sorry if I'm missing something obvious, but could you describe that scenario in a little more detail?
