### ISSUE TITLE
Top status bar & soft buttons showing when locked.

### ISSUE THREAD

**Issue by jezmck** [mclear/Android_NFC_Ring_Unlock#56]
![screenshot_2014-04-07-07-45-21](https://cloud.githubusercontent.com/assets/89996/2630104/0ae451d8-be43-11e3-8bc7-092efdaa2c8d.png)

You can even see the recently used apps list behind the top bar which was opened using the soft button.

Possibly caused by Alarm ringing when locked.

**Comment by r2DoesInc** [comment]
Look at the setting, "use without lockscreen". Please be careful and read the warnings.
