### ISSUE TITLE
unlock app activities (set app to active/inactive)

### ISSUE THREAD

**Issue by rogersmithbigo** [mclear/Android_NFC_Ring_Unlock#58]
im trying to use an app called trigger to toggle the nfc ring unlock app from active to inactive and back using your supplied extra nfc tag.  my options for an activity are as follows : co...devicelockedactivity, co...splash, co...unlockactivity and co...filechooseractivity.  im just guessing, but none of those seem to pertain to marking the app as active or inactive.

**Comment by jezmck** [comment]
I too use Trigger and think these apps really have to work together.

**Comment by r2DoesInc** [comment]
The app cannot be activated or deactivated currently by any outside means. The core NFCSecure app has a Tasker/Locale plugin, perhaps that could be brought over eventually.

**Comment by JohnMcLear** [comment]
@rogersmithbigo @jezmck let's create as much noise as possible by getting people to vote this feature up and we will get it implemented :)

**Comment by jezmck** [comment]
+1

**Comment by JohnMcLear** [comment]
We now support Tasker! :) Woop  http://blog.nfcring.com/how-to/how-to-nfc-ring-unlock-and-tasker-tutorial/
