### ISSUE TITLE
call behavior : "re-lock right away" wont stick, reverts to "do not re-lock"

### ISSUE THREAD

**Issue by rogersmithbigo** [mclear/Android_NFC_Ring_Unlock#59]
under call managment settings "disconnected phone call behaviour" keeps reverting back to "do not re-lock"  from "re-lock right away"

**Comment by JohnMcLear** [comment]
@r2DoesInc is this still the case?

**Comment by Lokki-P** [comment]
Same behaviour noted in current version, phone stays active after call until locked .

**Comment by JohnMcLear** [comment]
@Lokki-P Thanks :)
