### ISSUE TITLE
Homescreen Icon Text

### ISSUE THREAD

**Issue by IaisonQ** [mclear/Android_NFC_Ring_Unlock#6]
The NFC Unlock app currently reports its name on the home screen icon as 'co.mclear.nfcringunlock'

**Comment by fgsguedes** [comment]
For me it only reports its name as its package under 'Settings' -> 'Apps' -> 'Downloaded'.

**Comment by TheCustomCave** [comment]
I had that after uninstalling the previous version (which showed that name on the homescreen too). When I installed the new version, it had the same name and was in the same location. I removed the icon and added it back on the homescreen from within the app menu and it's now reporting the correct name.

**Comment by JohnMcLear** [comment]
Yea this is resolved :) Make sure you install the latest version from the play store!
