### ISSUE TITLE
NFC Unlock App doesn't always lock

### ISSUE THREAD

**Issue by khimera80** [mclear/Android_NFC_Ring_Unlock#60]
I've had this happen several times by now. Unfortunately, I can't reproduce it reliably. It almost seems like that if the screen is off for a longer time, the display won't be locked when the screen comes back on. Immediately toggling the screen again locks properly.
I'd say about once in 20 times this will happen (if the phone is left alone for a while).

I'm on Android 4.4.2, Nexus 5, Nova Launcher (in case that matters at all).

**Comment by JohnMcLear** [comment]
@khimera80 we're still unable to replicate this, is it something you are still experiencing?

**Comment by khimera80** [comment]
Yes, from time to time. Unfortunately I have no way to prove it, as it is totally random, so I can't even film it or screen record or anything. I am fairly certain it happens only if the phone sat around idly for a while, though even then it's not all the time. As I said, display off/on again fixes the problem immediately. 

I can try and hook the phone up to adb and hope for the problem to reappear. Though as these things tend to go, it probably won't ;-)

**Comment by JohnMcLear** [comment]
Any luck replicating this yet or can I close this issue?

**Comment by khimera80** [comment]
Sorry @JohnMcLear , yes, I have it daily, but no, unfortunately, haven't been able to capture it on video or with a cable attached yet.

If you wish, you can close this, and once I have "proof", I will reopen.

**Comment by Sopamo** [comment]
I just did notice a szenario when it happens. The unlock app just updated an the first time I switched my Nexus 4 on the phone was already unlocked.
This might not be @khimera80's issue but it is one thing to look into.

**Comment by doktorJung** [comment]
I've noticed the occasional non-lock as well, also on a Nexus 5, although now with 4.4.3,  I'll try and document the next time I see it and the situation.  I'd prefer to use the NFC Lock without a separate lockscreen, but the intermittent non-lock has me paranoid about accidentally mashing something if the screen turns on with no locking of any kind present...

**Comment by Lokki-P** [comment]
@Sopamo this is expected, on update you need to verify settings and re enable the app. Might be applicable to some of the other comments here.

**Comment by Sopamo** [comment]
@Lokki-P Well, but isn't that kind of a security issue? Given someone steals / finds my phone, he just has to wait until the next NFC Ring update unlocks it for him.

**Comment by Lokki-P** [comment]
If you feel it's a real security issue then you could probably take the app off auto update and do it manually when there's a new version available.

**Comment by Sopamo** [comment]
@Lokki-P yeah, didn't think of that. I'll do that. Maybe you should state somewhere, that the app disables itself on update so people know about it. I wouldn't expect it.
Thanks for your help!

**Comment by JohnMcLear** [comment]
@r2DoesInc I assume we disable device security on update in case I push out a bad update and nuke people out of their devices?

**Comment by Sopamo** [comment]
@JohnMcLear That would be kind of a rough reason in my opinion. I assumed it was kind of a technical issue.

**Comment by Lokki-P** [comment]
I was under the impression that this happened because of previous reports of being locked out after update.

**Comment by JohnMcLear** [comment]
Closing as this is expected behaviour :)
