### ISSUE TITLE
PIN Code numbers visible when PIN is entered

### ISSUE THREAD

**Issue by khimera80** [mclear/Android_NFC_Ring_Unlock#61]
If a backup code is set and you enter it, the edit field will show the entered number for a short amount of time.

I know that this is the behaviour of the EditText, however, i think it's a risk, especially given that the code can only be 4 characters long.

**Comment by jezmck** [comment]
Can we also make the buttons bigger?

**Comment by JohnMcLear** [comment]
@khimera80 @jezmck If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by r2DoesInc** [comment]
resolved
