### ISSUE TITLE
Allow more than 4 characters for PIN

### ISSUE THREAD

**Issue by khimera80** [mclear/Android_NFC_Ring_Unlock#62]
Please allow longer than 4 digit PINs.

**Comment by JohnMcLear** [comment]
@khimera80 If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by Lokki-P** [comment]
+1
More than 4/alphanumeric

**Comment by khimera80** [comment]
@JohnMcLear Thanks for responding. How do I do that though? :) Probably not a lot of people read this issue tracker..

**Comment by JohnMcLear** [comment]
@khimera80 talk with people on social networks / the forum etc.  Try to get others interested in the issue.  The more people who +1 it the sooner we add it as a feature.

**Comment by friode** [comment]
+1

**Comment by r2DoesInc** [comment]
resolved
