### ISSUE TITLE
Show clock on lock screen

### ISSUE THREAD

**Issue by khimera80** [mclear/Android_NFC_Ring_Unlock#63]
I often use my phone as a clock, and I'm sure I'm not alone doing this :)

Please put a small clock field on the lock screen, if not too much of a hassle, even if it's only updated once when the screen is activated.

Unless I'm missing a way to put widgets on.

**Comment by r2DoesInc** [comment]
Ive actually been looking into widget hosting for the main NFCSecure app, perhaps it'll make its way over down the road.

**Comment by JohnMcLear** [comment]
@khimera80  If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by jezmck** [comment]
+1

**Comment by ckoehnen** [comment]
+1

**Comment by ckoehnen** [comment]
@JohnMcLear 
@r2DoesInc 

Widget hosting sounds like an extensive task. As a quick solution you might allow a macro in the welcome message like {$time}, which will be replaced on device wake-up with the system's current time. This should only require 2-4 lines of code, but solve the issue for many people in a quick manner. 

May you consider this, please?

**Comment by r2DoesInc** [comment]
Your solution would not be that simple, rather than attempting to manage
the clock myself, using a widget offloads all the work onto the right parts
of the OS.

Widgets are in the core app, bringing them over here wouldn't be too
difficult at this point.

**Comment by ckoehnen** [comment]
This sounds great! I'm really looking forward seeing widgets in the unlock app soon. Do you have a schedule for the roadmap concerning this?

**Comment by JohnMcLear** [comment]
@ckoehnen It's just a case of raising enough funds to pay for it really, that's something we're working on.  Each sale helps though so spam social networks and get people involved..  Also if you want it as a priority get more +1's on this issue :)

**Comment by sisinoz** [comment]
+1

**Comment by EduardFriesen** [comment]
+1

**Comment by gth** [comment]
+1

**Comment by YngF** [comment]
+1

**Comment by choffee** [comment]
+1

**Comment by TJ-G** [comment]
+1

Even just a plain text clock on the lock screen would be great... just need a quick way to check the time like the standard android lockscreen has.

**Comment by JohnMcLear** [comment]
Widgets are now available :) Enjoy!
