### ISSUE TITLE
Typos in customisation settings screen

### ISSUE THREAD

**Issue by jezmck** [mclear/Android_NFC_Ring_Unlock#65]
The American spelling aside, there's an extra N.

**Comment by JohnMcLear** [comment]
@r2DoesInc did this make it's way into the latest fixes? Seems so minor it's worth doing just while you are at it?

**Comment by r2DoesInc** [comment]
No, but i can get to it tomorrow i suppose

**Comment by JohnMcLear** [comment]
Done :)
