### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Sopamo** [mclear/Android_NFC_Ring_Unlock#67]
I just had my phone laying in front of me (locked) on my desk. I got a call - didn't accept it - but afterwards the phone was unlocked! I didn't even come near with my ring. I have the setting "Incoming Phone Call Behaviour" set to "Do not disable on phone ring"

I forgot to add some infos:
The issue occured on my Nexus 4 with stock Android 4.4.2

**Comment by JohnMcLear** [comment]
This got closed with no follow up?  @r2DoesInc what's the deal?

**Comment by Sopamo** [comment]
I don't get it either.
At least an explanation would be nice. Thanks @JohnMcLear for clearing this up.

**Comment by r2DoesInc** [comment]
Was part of the issue with the phone settings not sticking I believe. Closed it when I clossed the other related tickets.
