### ISSUE TITLE
Require PIN Before enabling ring unlock

### ISSUE THREAD

**Issue by theckman** [mclear/Android_NFC_Ring_Unlock#68]
I spoke with @JohnMcLear the other evening. After I accidentally locked myself out of my phone, the idea came up that we should require a PIN to be entered prior to enabling the screen unlock mechanism.

**Comment by JohnMcLear** [comment]
If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by Lokki-P** [comment]
+1 Agreed
Mandatory pin code as secondary unlock method with pin code verification at initial setup.

**Comment by TheCustomCave** [comment]
+1 Agreed, it would certainly be more useful to the user than trying to remember their google account details. Especially given the users I work with on a daily basis who're interested in the ring.

**Comment by MHauge** [comment]
+1

**Comment by JohnMcLear** [comment]
Done :)
