### ISSUE TITLE
Verify PIN number when entering it in to the software

### ISSUE THREAD

**Issue by theckman** [mclear/Android_NFC_Ring_Unlock#69]
From a discussion with @JohnMcLear -- When setting a new PIN you should verify the PIN entry. It only asks for the PIN once and never confirms

**Comment by JohnMcLear** [comment]
If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by Lokki-P** [comment]
+1
This really should be standardised behaviour with a pin/code entry.

**Comment by TheCustomCave** [comment]
+1
Agreed

**Comment by khimera80** [comment]
+1 For the aforementioned reasons

**Comment by r2DoesInc** [comment]
resolved
