### ISSUE TITLE
Verify working NFC tag when enabling lock mechanism

### ISSUE THREAD

**Issue by theckman** [mclear/Android_NFC_Ring_Unlock#71]
I'm going to use GitHub 2-factor authentication as an example here. When enabling 2fa, the final step is for you to enter a valid token to ensure you have it configured and the device is working. The app should have the same, but with an unlock tag.

Before the locking mechanism can be enabled the user must scan their ring so the application can confirm they have a working tag.

If there is no working tag it will bail out and instruct them to register a new tag.

**Comment by JohnMcLear** [comment]
If you/others are eager to see this please get others to comment on this thread with a +1

**Comment by Lokki-P** [comment]
+1
Save the unwary...
At the very least force pin code secondary method before enable.

**Comment by TheCustomCave** [comment]
+1
Agreed

**Comment by sisinoz** [comment]
+1

**Comment by r2DoesInc** [comment]
resolved
