### ISSUE TITLE
Deadlocked when Ring is lost

### ISSUE THREAD

**Issue by stevenroose** [mclear/Android_NFC_Ring_Unlock#73]
I once did not have the ring with me and the lock screen came up (it shouldn't have done this, but that's a [different issue](https://github.com/mclear/Android_NFC_Ring_Unlock/issues/47)).

When I couldn't unlock with NFC, the app required me to enter my Google login details. However, I had my internet connections disabled (I was abroad). This made it impossible for the app to verify me login details, always rejecting them. This locked me out of the app until I had the ring back. This should not be like this, if I had lost the ring I would have needed to factory reset my phone.

I've seen this problem before: my brother once had someone enter a large number of incorrect unlock patterns in the default lock screen and it also required him to enter his Google login, which could not be verified due to missing internet connection. He had to reset his phone in order to use it again...

**Comment by JohnMcLear** [comment]
Different issue is resolved.

We have another open issue for this for requiring a pin code which we're going to implement..

Thanks fr reporting @stevenroose
