### ISSUE TITLE
*FIXED* NFC Unlock does not save the option in Disconnected Phone Call Behavior

### ISSUE THREAD

**Issue by grotesk86** [mclear/Android_NFC_Ring_Unlock#80]
Hi,

when i try to activate the "Re-lock the device right after the call is disconnected" it appears alright, but after i check the setting again is it on the option "do not re-lock the device". So it seems the setting is not saved. 

Best regards
Andreas

**Comment by JohnMcLear** [comment]
We already fixed this, please update your app and test again :)

**Comment by grotesk86** [comment]
Thanks for the fast answer, I'm on the version 1.5.7 and there is no update for the app in the playstore :(

**Comment by JohnMcLear** [comment]
@grotesk86 I just pushed 1.5.9 from beta to production, you should be able to get it now, let me know if that fixes it for you, thanks! :)

**Comment by grotesk86** [comment]
still no update online, could you provide me an apk file?

**Comment by JohnMcLear** [comment]
Version
    Uploaded on Status  Actions
43 (1.5.9)

12 May 2014

in Prod

**Comment by grotesk86** [comment]
Ok thanks got the update now and every thing is working right now :) i got the ring today and so i'm testing it a little bit ;) Til now i can really say it makes my finger smarter!

**Comment by JohnMcLear** [comment]
Oh ho :) Enjoy! :)
