### ISSUE TITLE
Ring Does Not Unlock My LG G Flex Android Phone

### ISSUE THREAD

**Issue by cavebear541** [mclear/Android_NFC_Ring_Unlock#84]
The ring will unlock the application, but when I set the application to Active mode the ring does not register.

**Comment by Dmole** [comment]
Related:
https://github.com/mclear/Android_NFC_Ring_Unlock/issues/90

**Comment by JohnMcLear** [comment]
Can you provide steps to replicate this issue please?

**Comment by Lokki-P** [comment]
Confusing enable/disable button appears to be the root cause here. Users appear to be changing the switch to show 'enable'. Application is working, this is user confusion.

**Comment by JohnMcLear** [comment]
@r2DoesInc you seemed to change this, any reason why?

**Comment by r2DoesInc** [comment]
Theres no more switch, the latest updtes with the confirm to turn on screen required me to redo that portion a bit.
