### ISSUE TITLE
Unable to unlock during incoming call

### ISSUE THREAD

**Issue by doktorJung** [mclear/Android_NFC_Ring_Unlock#86]
Hi, I'm using The NFC Ring Unlock app, version 1.5.1112 on a Nexus 5, running 4.4.3 stock.  I've noticed that the Unlock app seems to prevent me from unlocking the phone during phone calls!  I've tried it with unlock on incoming call enabled and disabled, and in either case I get a lock screen that I can't dismiss via the ring until the call ends.  I like the app otherwise, but it seems to have removed the 'phone' functionality from my phone, at least for incoming calls.

**Comment by doktorJung** [comment]
(Fixed the title, accidentally labeled as 'unable to lock during call' whoops!)

**Comment by Lokki-P** [comment]
Have you set behaviours on incoming call correctly?

**Comment by doktorJung** [comment]
I have them set, don't know about correctly.  Should setting it to not unlock on an incoming call prevent it from being unlocked via the ring?  I've tried unlock on call and don't unlock on call, as far as I can tell, without much success.

**Comment by Lokki-P** [comment]
Ah, I see. If you set to unlock on incoming, no lock on answer, re lock on disconnect that should solve those issues. Its not beyond the bounds of reason that the unlock failure during the call is hardware/RF interference related.

**Comment by doktorJung** [comment]
Alright, I've set it as you've suggested.  I'll try testing it when I'm around another phone, thanks!

**Comment by doktorJung** [comment]
No, still locked on incoming calls.  I saw an update mention on-ring settings, perhaps I should test it again?  

Edit: settings as suggested above, and was able to unlock immediately following the call.

**Comment by Lokki-P** [comment]
Sorry for the delay, can you clarify if that update solved the issue for you?

**Comment by doktorJung** [comment]
I believe it has - I currently see the pick-up/hang-up screen on an incoming call, without a need to scan my ring.  I may test it with unlock on ring turned off, but the current behavior is acceptable.  Thanks for the follow-up!
