### ISSUE TITLE
app fails to respect lock setting

### ISSUE THREAD

**Issue by Dmole** [mclear/Android_NFC_Ring_Unlock#91]
app fails to respect lock setting.
I set my phone to turn off the display when the power button is pushed.
it will lock after 30min of no use.
I have an Icon to lock it instantly.
when the nfc app is enabled it locks on the power button.

**Comment by JohnMcLear** [comment]
@Dmole sorry but I don't understand the issue here.

What behaviour do you expect and can you provide exact steps to replicate?

**Comment by Dmole** [comment]
expected:
- press the power button (display turners off)
- press the power button (home screen is shown)

actual:
- press the power button (display turners off)
- press the power button (lock screen is shown)

**Comment by JohnMcLear** [comment]
Are you running the latest version?   This was an old bug.. 

Are you sure Device Security is disabled?

**Comment by Dmole** [comment]
I'm running 1.5.1112 the current version on google play. regarding 'Device Security'  Please re-read the first post.  'Settings > my device > lock screen > lock instantly with power key' is not being respected. might not be a setting shown by aosp

**Comment by JohnMcLear** [comment]
@r2DoesInc any thoughts on this?

**Comment by Lokki-P** [comment]
You are able to set a lock timer for the unlock app which will stop it from locking immediately on using the sleep function of the phone. Set unlock delay type to timeout then set time required.

**Comment by r2DoesInc** [comment]
android lockscreen settings != the app lockscreen settings. they are completely different.
