### ISSUE TITLE
photo option has no effect

### ISSUE THREAD

**Issue by Dmole** [mclear/Android_NFC_Ring_Unlock#93]
When adding a key you can take a photo of it but you will never see that photo.

**Comment by JohnMcLear** [comment]
They are seen under "Manage Keys"

**Comment by Dmole** [comment]
Yes that's where they should be shown Only they are not actually displayed, just the placeholder.

**Comment by JohnMcLear** [comment]
They show fine for me ;\  Can you please confirm / provide exact steps to replicate.

**Comment by Dmole** [comment]
Please close this ticket;
Seems to be working now.
(maybe I neglected to press save before)
