### ISSUE TITLE
.

### ISSUE THREAD

**Issue by GilliamOperator** [mclear/Android_NFC_Ring_Unlock#94]
.

**Comment by JohnMcLear** [comment]
NFC unlock would need to be part of Android core for us to be able to provide this.

**Comment by Lokki-P** [comment]
Can you use a lock screen removal application to get around this?

**Comment by Lokki-P** [comment]
Excellent, that's the best solution at this point.

**Comment by JohnMcLear** [comment]
@YopparaiNeko do you require root for that app?

**Comment by Lokki-P** [comment]
No Lock app doesn't require root, needs re enabling after reboot though.

**Comment by JohnMcLear** [comment]
@Lokki-P @YopparaiNeko can we please document what apps you used to negate this issue?  It's possible we can introduce that apps functionality into NFC Ring Unlock however for now using a third party app is a fine workaround :)

I'm closing this as it's resolved but I think an item in the Wiki to document the fix would be ideal please :)

**Comment by Lokki-P** [comment]
Done.

**Comment by JohnMcLear** [comment]
Okay thanks would you mind adding that info to the wiki please?

----- Reply message -----

**Comment by JohnMcLear** [comment]
Yea that works for me, ideally open source alternatives will be closer to the top, I don't think we can really promote paid alternatives if they are also closed source.

**Comment by JohnMcLear** [comment]
@Lokki-P did this land on the forum?  If so we can close this issue :)

**Comment by Lokki-P** [comment]
Forum plus update to wiki-thing IIRC. All good, close it up.

**Comment by JohnMcLear** [comment]
Tnx
