### ISSUE TITLE
Facebook chat heads

### ISSUE THREAD

**Issue by LittleJohnD** [mclear/Android_NFC_Ring_Unlock#99]
Hi, running app version 1.5.1112 and android 4.4.2 HTC one.

Facebook chat head still on top of every thing but you cannot do anything with it.

**Comment by JohnMcLear** [comment]
This sounds like a facebook app bug as opposed to a bug with the app?  What do you expect the behaviour to be?

**Comment by LittleJohnD** [comment]
I think the Facebook app forces itself to the top activity. I would expect the lock screen hide everything that is running on the phone I can attach a screen shot if needed.

**Comment by JohnMcLear** [comment]
I think this is something Facebook will need to change!

----- Reply message -----

**Comment by r2DoesInc** [comment]
"Use with no lockscreen" and disabling your stock lockscreen will draw the app over facebooks stuff.

**Comment by LittleJohnD** [comment]
I'm on kitkat and can't remove my lockscreen. I have to swipe even though I have no protection other than the nfcring app
http://forums.androidcentral.com/htc-one/364294-htc-one-cant-disable-lock-screen-now-kitkat-update.html

**Comment by Lokki-P** [comment]
Try a third party app from play store. No Lock works well for me. Swipe will re enable on reboot, I haven't tried yet to see what happens with "no lock screen" flag set.

**Comment by LittleJohnD** [comment]
Just tried no lock with no lock screen flag and first time reset and used lock screen second time worked as expected. Thanks Lokki for the 3rd party app. Been considering one but permissions look a little dodgy.

**Comment by LittleJohnD** [comment]
The third-party app has fixed the issue though.
